In [29]:
def question1(a):
    x = np.arange(9)+a
    arr_2d = np.reshape(x, (3, 3))
    return arr_2d

In [8]:
import numpy as np

x = np.array([[3], [4], [4]])
y = np.array([[5], [7], [9]])
np.hstack((x,y))

array([[3, 5],
       [5, 7],
       [7, 9]])

In [28]:
a = 3

arr_2d

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
question1(3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
def question2(x):
    if any(x<0):
        return x
    else:
        array_int16 = x.astype(np.uint16)
        return array_int16


In [44]:
question2(np.array([10.2, -3.1, 9.33]))

array([10.2 , -3.1 ,  9.33])

In [53]:
def question3(a):
    y = np.zeros((a,a))
    y[1:-1,1:-1] = 1
    return y

In [54]:

question3(4)

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [60]:
x = np.asarray([1, 5, 10, 20, 30])
y = np.asarray([1, 1.2, 1.8, 3, 10])
# y = f(x)

In [63]:
import scipy.interpolate as sc
f = sc.interp1d(x, y, kind='quadratic')
f(11)

array(1.89123707)